spring:
  application:
    name: testapp

server:
  port: 443
  ssl:
    key-store: classpath:dlt.p12
    key-store-password: ipcc@95598
    keyStoreType: PKCS12
    keyAlias: root
#日志
logging:
  config: classpath:logback-spring.xml
  level:
    dao: debug
    org:
      mybatis: debug
http:
  port: 80